Admin/Models/Role.php
<?php

namespace App\Admin\Models;

use App\Admin\Observers\RoleObserver;

class Role extends \Spatie\Permission\Models\Role
{

    /*
  |--------------------------------------------------------------------------
  | FUNCTIONS
  |--------------------------------------------------------------------------
  */
    protected static function boot()
    {
        parent::boot();

        Role::observe(RoleObserver::class);
    }

//    public function permissions(): BelongsToMany
//    {
//        return $this->belongsToMany(
//            config('permission.models.permission'),
//            config('permission.table_names.role_has_permissions'),
//            'role_id',
//            'permission_id'
//        );
//    }
//
//    /**
//     * A role belongs to some users of the model associated with its guard.
//     */
//    public function users(): MorphToMany
//    {
//        return $this->morphedByMany(
//            getModelForGuard($this->attributes['guard_name']),
//            'model',
//            config('permission.table_names.model_has_roles'),
//            'role_id',
//            config('permission.column_names.model_morph_key')
//        );
//    }
//
}

Admin/Http/Controllers/RoleController.php
<?php

namespace App\Admin\Http\Controllers;

use App\Admin\{Constants\RoleConstant as Constant,
    Http\Services\RoleService as ModelService,
    Models\Role as Model,
    Models\Permission};

use Illuminate\Http\Request;

class RoleController extends BaseAdminController
{
    private $sv;

    public function __construct(ModelService $modelService)
    {
        $this->middleware('permission:role_view', ['only' => ['index', 'show']]);
        $this->middleware('permission:role_create', ['only' => ['create', 'store']]);
        $this->middleware('permission:role_edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:role_destroy', ['only' => ['destroy']]);

        $constant = Constant::class;
        $this->sv = $modelService;
        $permissions_pluck = Permission::guardName('admin')->get()->pluck('name_note', 'id');
        view()->share([
            'permissions_pluck' => $permissions_pluck,
            'constant'          => $constant,
        ]);
    }

    public function index()
    {
        $title = __('role.meta_title.index');
        return view('admin::role.index', compact('title'));
    }

    public function grid(Request $request)
    {
        $limit = $request->limit;
        $s = getSortAdmin($request);
        $docs = Model::with('users:username')->withCount('users')->withCount('permissions')->orderBy($s[0], $s[1]);
        if ($request->search) {
            $docs = $docs->where(function ($query) use ($request) {
                $query->where('name', 'like', '%' . $request->search . '%');
            });
        }
        $docs = $docs->paginate($limit);
        return view('admin::role.grid', compact('docs'));
    }

    public function create()
    {
        $title = __("role.new");
        return view('admin::layouts.create', compact('title'));
    }

    public function edit(Model $role)
    {
        $doc = $role->load('permissions');
        $title = __("role.edit") . " ( $doc->name )";
        return view('admin::layouts.create', compact('title', 'doc'));
    }

    public function store(Request $request)
    {
        $table = Constant::TABLE;
        $name_min_len = Constant::VALIDATE['name_min_len'];
        $name_max_len = Constant::VALIDATE['name_max_len'];

        $request->validate([
            'name'           => "required|min:$name_min_len|max:$name_max_len|unique:$table",
            'guard_name'     => "in:admin",
            'permission_ids' => "required",
        ]);
        $this->sv->create($request, ['permission_ids']);
        flash()->success(__('message.success.create'));
        return redirect_route_admin('role.index');
    }


    public function update(Request $request, Model $role)
    {
        $doc = $role;
        $table = Constant::TABLE;
        $name_min_len = Constant::VALIDATE['name_min_len'];
        $name_max_len = Constant::VALIDATE['name_max_len'];

        $request->validate([
            'name'           => ["required", "min:$name_min_len", "max:$name_max_len", "unique:$table,name,$doc->id"],
            'guard_name'     => "in:admin",
            'permission_ids' => "required",
        ]);

        $this->sv->update($request, $doc, ['permission_ids']);
        flash()->success(__('message.success.update'));
        return redirect_route_admin('role.index');
    }

    public function destroy(Model $role)
    {
        return $this->sv->destroy($role);
    }
}

Admin/resources/views/role/form.blade.php
<div class="row">
    <div class="col-12">
        <div class="ibox">
            <div class="ibox-title">
                <h5>Sửa nhóm quyền</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                </div>
            </div>

            <div class="ibox-content">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="form-group @error('name') has-error @enderror">
                                {!! Form::label('name', __("$type.name"), array('class' => ' required')) !!}
                                {!! Form::text('name', null, array('class' => 'form-control',
                                'placeholder'=> __("$type.name"),
                                'required' => true,
                                'minlength'=>$constant::VALIDATE['name_min_len'],
                                'maxlength'=>$constant::VALIDATE['name_max_len'])) !!}
                                <span class="help-block">{{ $errors->first('name', ':message') }}</span>
                            </div>
                        </div>

                        <div class="col-12 col-md-6">
                            <div class="form-group @error('guard_name') has-error @enderror">
                                {!! Form::label('guard_name', __("$type.guard_name"),array('class' => ' required')) !!}
                                {!! Form::select('guard_name', $constant::GUARD_NAME,null, array('class' => 'form-control')) !!}
                                <span class="help-block">{{ $errors->first('guard_name', ':message') }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="form-group @error('permission_ids') has-error @enderror">
                                {!! Form::label('permission_ids', __("$type.permissions"), array('class' => 'col-form-label required')) !!}
                                {!! Form::select('permission_ids[]', $permissions_pluck, @$doc->permissions, ['class' => 'form-control dual_select','multiple'=>true]) !!}
                                <span class="help-block">{{ $errors->first('permission_ids', ':message') }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ibox-footer">
                @include('admin::common._button_submit')
            </div>
        </div>
    </div>
</div>
@push('css')
    <link href="{{asset_admin('plugins/iCheck/custom.css')}}" rel="stylesheet">
    <link href="{{asset_admin('css/glyphicons.css')}}" rel="stylesheet">
    <link href="{{asset_admin('plugins/dualListbox/bootstrap-duallistbox.min.css')}}" rel="stylesheet">
@endpush

@push('js')
    <!-- iCheck -->
    <script src="{{asset_admin('plugins/iCheck/icheck.min.js')}}"></script>
    <script src="{{asset_admin('plugins/dualListbox/jquery.bootstrap-duallistbox.js')}}"></script>

    <script>
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });

        $('.dual_select').bootstrapDualListbox({
            selectorMinimalHeight: 160,
            filterPlaceHolder: 'Tìm kiếm',
            infoText: 'Hiện thị {0}',
            infoTextFiltered: '<span class="label label-warning">Kết quả lọc</span> {0} đến {1}',
            infoTextEmpty: 'Trống',
            filterTextClear: 'Xóa lọc',
            preserveSelectionOnMove: false,
            moveOnSelect: false,
        });
    </script>
@endpush

Admin/resources/views/role/grid.blade.php
<div class="table-responsive">
    <table class="data-table table table-striped table-bordered">
        <thead>
        <tr>
            <th class="table_stt sort" data-sort="id">ID</th>
            <th class="sort" data-sort="name">{{__("admin::$type.name")}}</th>
            <th>{{__("admin::$type.count_admin_use")}}</th>
            <th>{{__("admin::$type.count_permissions")}} / Tổng ({{count($permissions_pluck)}})</th>
            <th class="sort" data-sort="created_at">Ngày tạo</th>
            <th class="sort" data-sort="updated_at">Ngày sửa cuối</th>
            @include('admin::common.th_action_table')
        </tr>
        </thead>
        <tbody>
        @if(count($docs))
            @foreach($docs as $key => $doc)
                <tr>
                    <td class="table_id"> {{$doc->id}} </td>
                    <td>{{$doc->name}}</td>
                    <td title="{{@str_replace(array('[',']','"'),'', $doc->users()->pluck('username'))}}">{{$doc->users_count}}</td>
                    <td title="{{@str_replace(array('[',']','"'),'', $doc->permissions()->pluck('name'))}}">{{$doc->permissions_count}}</td>
                    <td>{{$doc->created_at->format($constant::FORMAT_DATE_TIME)}}</td>
                    <td>{{$doc->updated_at->format($constant::FORMAT_DATE_TIME)}}</td>
                    @include('admin::common.th_edit_delete_table')
                </tr>
            @endforeach
        @else
            <tr>
                <td class="no-data"></td>
            </tr>
        @endif
        </tbody>
    </table>
</div>

@include('admin::common.gridFooter')

Admin/resources/views/role/index.blade.php
@extends('admin::layouts.index')

@section('body')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Danh sách nhóm quyền</h5>
                </div>
                <div class="ibox-content">
                    <div class="noi_dung_table">
                        <div class="gridTable"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection